Fix goimports and golint CI (#67)

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -14,12 +14,12 @@ jobs:
       max-parallel: 1
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
-        go_version: ['1.15', '1.16']
+        go_version: ['1.17', '1.18']
 
     steps:
 
     - name: Set up Go version
-      uses: actions/setup-go@v2
+      uses: actions/setup-go@v3
       with:
         go-version: ${{ matrix.go_version }}
 
@@ -32,32 +32,36 @@ jobs:
         aws-region: us-east-2
 
     - name: Check out code into the Go module directory
-      uses: actions/checkout@v2.0.0
+      uses: actions/checkout@v3
 
     - name: Build
       run: go build -v ./...
-    
+
     - name: Unit and Integration Tests
       run: go test -v -timeout 20m ./...
-  
-  imports:
-    name: goimports
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@master
-    - name: check
-      uses: grandcolline/golang-github-actions@v1.1.0
-      with:
-        run: imports
-        token: ${{ secrets.GITHUB_TOKEN }}
 
-  lint:
-    name: Lint
+  check:
+    name: Perform style and linter check
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@master
-    - name: check
-      uses: grandcolline/golang-github-actions@v1.1.0
-      with:
-        run: lint
-        token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Set up Go version
+        uses: actions/setup-go@v3
+        with:
+          go-version: '1.18'
+      - name: Install goimports
+        run: go install golang.org/x/tools/cmd/goimports@latest
+      - name: Check out code into the Go module directory
+        uses: actions/checkout@v3
+      - run: goimports -w .
+      - run: go mod tidy
+      # If there are any diffs from goimports or go mod tidy, fail.
+      - name: Verify no changes from goimports and go mod tidy
+        run: |
+          if [ -n "$(git status --porcelain)" ]; then
+            exit 1
+          fi
+      - run: go vet ./...
+      - uses: dominikh/staticcheck-action@v1.2.0
+        with:
+          version: "2022.1"
+          install-go: false
